POST localhost:8080/deploy
Content-Type: application/json

{
  "name": "a"
  ,"version": 3
}

###
POST localhost:8080/deploy
Content-Type: application/json

{
  "name": "b"
  ,"version": 2
}

###
GET localhost:8080/services?systemVersion=0
Content-Type: application/json
