version: '3.8'

services:
  releasemanager:
    image: tset/releasemanager
    restart: "no"
    expose:
      - 8080
    ports:
      - "8080:8080"
    networks:
      - net
    depends_on:
      - releasemanager-db
  releasemanager-db:
    image: postgres:13
    restart: "no"
    environment:
      POSTGRES_PASSWORD: releasemanager
      POSTGRES_DB: releasemanager
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - net
networks:
  net: